# Generated by Django 3.0.7 on 2020-07-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjstore_main', '0011_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
