# Generated by Django 3.0.7 on 2020-07-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjstore_main', '0012_order_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'In Order'), (2, 'Pending'), (3, 'In delivery'), (4, 'Delivered'), (5, 'Cancelled')], default=1),
        ),
    ]
